default_context:
  project_name: 'codingnetworks_automations'
  project_slug: 'codingnetworks_automations'
  domain_main: 'codingnetworks.com'
  domain_staging: 'stag.codingnetworks.com'
  docker_swarm_stack_name_main: 'codingnetworks-com'
  docker_swarm_stack_name_staging: 'stag-codingnetworks-com'
  secret_key: '6ed0d6fc3c3868d887fbc6bc117295b54f780a593a9ab04888d6353b9c46da27'
  first_superuser: 'admin@codingnetworks.com'
  first_superuser_password: '21dc11ebf891633233a436a5cc667e725c2632e02860e2ee51961945648c461d'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.codingnetworks.com", "https://stag.codingnetworks.com", "https://codingnetworks.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: 'smtp.gmail.com'
  smtp_user: 'codingnetworks@gmail.com'
  smtp_password: ''
  smtp_emails_from_email: 'info@codingnetworks.com'
  postgres_password: '8af442f588e8d71a33b4e9d0e1b592a95ad8bd1995d80935f1fab35a77076d81'
  pgadmin_default_user: 'admin@codingnetworks.com'
  pgadmin_default_user_password: '21dc11ebf891633233a436a5cc667e725c2632e02860e2ee51961945648c461d'
  traefik_constraint_tag: 'codingnetworks.com'
  traefik_constraint_tag_staging: 'stag.codingnetworks.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:21dc11ebf891633233a436a5cc667e725c2632e02860e2ee51961945648c461d'
  sentry_dsn: ''
  docker_image_prefix: 'registry.gitlab.com/codingnetworks/codingnetworks'
  docker_image_backend: 'registry.gitlab.com/codingnetworks/codingnetworks/backend'
  docker_image_celeryworker: 'registry.gitlab.com/codingnetworks/codingnetworks/celeryworker'
  docker_image_frontend: 'registry.gitlab.com/codingnetworks/codingnetworks/frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
